### PR TITLE
Avoid potential UB from isize to pointer transmute.

### LINKED ISSUE #7: Crash in release but not debug
When running `ddc_winapi::Monitor::enumerate()` in debug mode, it works as expected. When running in release mode, it immediately crashes the program with exit code `0xc000041d`. This happens on master (618a2908bb6e5779753c5cdb377653b8e1dba75b) as well.

This is on Rust 1.78.0, Windows 11.

Not sure what else to say, let me know if there's any more information I can provide.

### PR DESCRIPTION
**Pull request by cr1901**
This should fix #7 (at the very least, it works locally for me). Targeting 0.2.x because that's what [I'm using](https://github.com/cr1901/swmon) right now :). Happy to add 0.3.x and main support when I upgrade deps.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -242,14 +242,14 @@ pub fn get_physical_monitors_from_hmonitor(monitor: HMONITOR) -> io::Result<Vec<
...
-        let monitors: &mut Vec<HMONITOR> = mem::transmute(userdata);
+        let monitors: &mut Vec<HMONITOR> = &mut *(userdata as *mut Vec<HMONITOR>);
         monitors.push(monitor);
         TRUE
     }
 
     let mut monitors = Vec::<HMONITOR>::new();
     if unsafe {
-        let userdata = &mut monitors as *mut _;
+        let userdata = ptr::addr_of_mut!(monitors);
```
Comment (arcnmx) [inline src/lib.rs:252]: This might technically bump MSRV but that shouldn't really be a problem.

**Review by arcnmx — APPROVED** [review]

File: src/lib.rs (hunk 1 above)
Comment (cr1901) [reply src/lib.rs:252]: It's not clear to me whether the `&mut` in `let userdata = &mut monitors as *mut _;` is still in existence by the time the callback is called (at which point we convert to `*mut` back to `&mut`. If it _is_ still in existence, that's gonna be insta-UB that `rustc` doesn't optimize yet.

My gut feeling is that the original code is fine, but I'd want to ask other ppl working on provenance rules, formalizing the borrow checker, miri and the like what they think before reverting the code back to original (whenever I get around to that :P).

So in the interim, I used code to get rid of all but one `&mut`. In practice, the old code is probably fine for < "the version where `ptr::addr_of_mut` was introduced.
